"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 13:46:02.794509
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.Enum('audio', 'video', name='media_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.Enum('upload', 'import', 'extracted', 'trimmed', 'isolated', 'mixed', 'export', name='media_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('audio_codec', sa.String(length=64), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('parent_media_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_media_id'], ['media_assets.id'], name=op.f('fk_media_assets_parent_media_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_path', name=op.f('uq_media_assets_storage_path')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_media_assets_stored_filename'))
    )
    op.create_index(op.f('ix_media_assets_created_at'), 'media_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_assets_media_type'), 'media_assets', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_assets_parent_media_id'), 'media_assets', ['parent_media_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('isolate', 'mix', 'transcribe', 'export', 'import', name='job_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='job_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_media_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('output_media_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['input_media_id'], ['media_assets.id'], name=op.f('fk_processing_jobs_input_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_media_id'], ['media_assets.id'], name=op.f('fk_processing_jobs_output_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_processing_jobs_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_input_media_id'), 'processing_jobs', ['input_media_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_project_id'), 'processing_jobs', ['project_id'], unique=False)
    op.create_index('ix_processing_jobs_status_created_at', 'processing_jobs', ['status', 'created_at'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('track_type', sa.Enum('dialogue', 'music', 'sfx', 'other', name='track_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('volume >= 0 AND volume <= 4', name=op.f('ck_tracks_volume_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tracks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    op.create_index(op.f('ix_tracks_project_id'), 'tracks', ['project_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('timeline_start', sa.Float(), nullable=False),
    sa.Column('source_start', sa.Float(), nullable=False),
    sa.Column('source_end', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('fade_in', sa.Float(), nullable=False),
    sa.Column('fade_out', sa.Float(), nullable=False),
    sa.CheckConstraint('fade_in >= 0 AND fade_out >= 0', name=op.f('ck_clips_fades_non_negative')),
    sa.CheckConstraint('source_start >= 0 AND source_end > source_start', name=op.f('ck_clips_source_range')),
    sa.CheckConstraint('timeline_start >= 0', name=op.f('ck_clips_timeline_start_non_negative')),
    sa.CheckConstraint('volume >= 0 AND volume <= 4', name=op.f('ck_clips_volume_range')),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_clips_media_id_media_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_clips_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clips'))
    )
    op.create_index(op.f('ix_clips_media_id'), 'clips', ['media_id'], unique=False)
    op.create_index(op.f('ix_clips_track_id'), 'clips', ['track_id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_transcriptions_job_id_processing_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_transcriptions_media_id_media_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcriptions'))
    )
    op.create_index(op.f('ix_transcriptions_media_id'), 'transcriptions', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_media_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_clips_track_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_media_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_tracks_project_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('ix_processing_jobs_status_created_at', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_project_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_input_media_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('projects')
    op.drop_index(op.f('ix_media_assets_parent_media_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_media_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_created_at'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
